# node image
FROM node:14-alpine

# work directory for app
WORKDIR '/app'

# copy package.json and install dependencies
COPY package.json .
RUN npm install

# copy all content to container
COPY . .

# start app
CMD ["npm", "run", "start"]

