# This is a basic workflow to help you get started with Actions

name: CI Docker on AWS Elatic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Lastest Repo
        uses: actions/checkout@master
        
      - name: Generate Deployment Package
        run : zip -r deploy.zip * -x "**node_modules**"
        
      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id  : current-time
        
      - name: String Replace
        uses: frabert/replace-string-action@master
        id  : format-time
        with:
          pattern: '[:\.]+'
          string : "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
          
      - name: Deploy to ElasticBeanStalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrects.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrects.AWS_SECRET_ACCESS_KEY }}
          application_name: HandsOnDockerCICD
          environment_name: Handsondockercicd-env
          version_label: "HandsOnDockerCICD-${{ steps.format-time.outputs.replaced }}"
          region: us-east-2
          deployment_package: deploy.zip
          
          
